// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwvgEkKA6OQPecTDQ6dwFDmDyqE9MqPc',
    appId: '1:737646986218:web:9b5980a8499be58f92a893',
    messagingSenderId: '737646986218',
    projectId: 'agrimarket-6630a',
    authDomain: 'agrimarket-6630a.firebaseapp.com',
    databaseURL: 'https://agrimarket-6630a-default-rtdb.firebaseio.com',
    storageBucket: 'agrimarket-6630a.firebasestorage.app',
    measurementId: 'G-TBZ5G7CY3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEth4K4-c6n1fBKPSJPljRftLy9CI3y88',
    appId: '1:737646986218:android:da08ece8fba984b592a893',
    messagingSenderId: '737646986218',
    projectId: 'agrimarket-6630a',
    databaseURL: 'https://agrimarket-6630a-default-rtdb.firebaseio.com',
    storageBucket: 'agrimarket-6630a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpr-Hh67qGqfQUGf58Phfn3pVydGUEuOc',
    appId: '1:737646986218:ios:ce3a35788c08a9d192a893',
    messagingSenderId: '737646986218',
    projectId: 'agrimarket-6630a',
    storageBucket: 'agrimarket-6630a.firebasestorage.app',
    iosBundleId: 'com.example.agrimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpr-Hh67qGqfQUGf58Phfn3pVydGUEuOc',
    appId: '1:737646986218:ios:ce3a35788c08a9d192a893',
    messagingSenderId: '737646986218',
    projectId: 'agrimarket-6630a',
    storageBucket: 'agrimarket-6630a.firebasestorage.app',
    iosBundleId: 'com.example.agrimarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJwvgEkKA6OQPecTDQ6dwFDmDyqE9MqPc',
    appId: '1:737646986218:web:ba3496f7ecced25c92a893',
    messagingSenderId: '737646986218',
    projectId: 'agrimarket-6630a',
    authDomain: 'agrimarket-6630a.firebaseapp.com',
    storageBucket: 'agrimarket-6630a.firebasestorage.app',
    measurementId: 'G-11XFPBCQ44',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDJwvgEkKA6OQPecTDQ6dwFDmDyqE9MqPc',
    appId: '1:737646986218:linux:da08ece8fba984b592a893',
    messagingSenderId: '737646986218',
    projectId: 'agrimarket-6630a',
    authDomain: 'agrimarket-6630a.firebaseapp.com',
    storageBucket: 'agrimarket-6630a.firebasestorage.app',
    measurementId: 'G-TBZ5G7CY3L',
  );
}